### PR TITLE
added issue action

### PR DESCRIPTION
**Pull request by RemcoHalman**
if welcome message failed, sets a new issue.

As mentioned in #2

### CODE REVIEW

**Comment by eddiejaoude** [comment]
This is a great Action, however, I do not think the welcome message will ever fail. I think maybe this should be added to the documentation on this repo, so that when someone adds an Action that could fail, they know how to add this step to their Action. What do you think?

**Comment by RemcoHalman** [comment]
@eddiejaoude You are probably right on this 😄 ill change it up a little and get back to you

**Comment by eddiejaoude** [comment]
@RemcoHalman it could be in the `README` for now and we can move it later as the README grows

**Comment by adityaraute** [comment]
@RemcoHalman  Consider closing this PR, or marking it as draft, if it's not complete yet.

**Comment by suitupstan** [comment]
Hey just checking in, @RemcoHalman do you need any help?

**Comment by suitupstan** [comment]
Hey there @RemcoHalman 👋 Just checking in, do you need any help?

**Comment by adityaraute** [comment]
@RemcoHalman Please respond to the comments at your earliest.

**Comment by RemcoHalman** [comment]
@krishguptadev @adityaraute Hey there, Totally forgot about this swamped with working on the new job... I'll close the PR and if needed i'll try to pick it up again in the future.

**Pull request closed without merging**
